from __future__ import annotations

from typing import Protocol, TYPE_CHECKING

if TYPE_CHECKING:
    from slay_the_spire.content.catalog import WeightedPoolEntry
    from slay_the_spire.content.registries import (
        ActRegistry,
        CardRegistry,
        CharacterRegistry,
        EncounterRegistry,
        EnemyRegistry,
        EventRegistry,
        PotionRegistry,
        RelicRegistry,
    )


class ContentProviderPort(Protocol):
    def characters(self) -> "CharacterRegistry": ...

    def cards(self) -> "CardRegistry": ...

    def enemies(self) -> "EnemyRegistry": ...

    def encounters(self) -> "EncounterRegistry": ...

    def relics(self) -> "RelicRegistry": ...

    def potions(self) -> "PotionRegistry": ...

    def events(self) -> "EventRegistry": ...

    def acts(self) -> "ActRegistry": ...

    def enemy_ids_for_pool(self, pool_id: str) -> tuple[str, ...]: ...

    def enemy_pool_entries(self, pool_id: str) -> tuple["WeightedPoolEntry", ...]: ...

    def encounter_pool_entries(self, pool_id: str) -> tuple["WeightedPoolEntry", ...]: ...

    def event_ids_for_pool(self, pool_id: str) -> tuple[str, ...]: ...

    def event_pool_entries(self, pool_id: str) -> tuple["WeightedPoolEntry", ...]: ...

    def potion_ids_for_pool(self, pool_id: str) -> tuple[str, ...]: ...
